### ISSUE TITLE
Polyfill not working?

### ISSUE THREAD

**Issue by warpdesign** [es-shims/String.prototype.trimEnd#1]
I think there is a bug in your polyfill in case the string doesn't have spaces at the end but only at the begining.

Running `" test".trimEnd()` is supposed to return `" test"` but your polyfill will return `"test"` removing leading spaces.

**Comment by KhaledElAnsari** [comment]
Thank you, it is a valid issue indeed! I will fix it ASAP

**Comment by LemonyPie** [comment]
Hello @KhaledElAnsari is this polyfill used anywhere now?

I think it should look like this:

```
const trimmed = value.trim(); 
const index = value.indexOf(trimmed) 
return value.slice(0, index + trimmed.length) 
```

**Comment by ljharb** [comment]
v1.0.0 should fix this.
